"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, CircleDashed, ShieldCheck, Monitor, BookOpen, ListChecks, CalendarDays } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Action, Shell, Eyebrow, SectionHead, ReviewPreview, FAQList } from "@/components/tradeez";

function Intro({label,title,children,status}:{label:string;title:React.ReactNode;children:React.ReactNode;status?:string}){return <div className="page-intro"><Eyebrow>{label}</Eyebrow>{status&&<span className="status-tag intro-status">{status}</span>}<h1>{title}</h1><div className="intro-description">{children}</div></div>}
function Rows({rows}:{rows:string[][]}){return <div className="text-rows">{rows.map(([title,text],i)=><div key={title}><span className="row-index mono">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div>}
function PageEnd({title,description,href,label}:{title:string;description:string;href:string;label:string}){return <section className="page-end"><div className="container"><div><h2>{title}</h2><p>{description}</p></div><Action href={href}>{label}</Action></div></section>}

function EAPreview(){return <div className="ea-preview"><div className="ea-topbar"><strong>TradeEZ<span> / SOP</span></strong><span className="status-tag">面板结构示意</span></div><div className="ea-market"><div><span className="micro">METATRADER 5</span><h3>XAUUSD</h3></div><div className="market-state"><span className="state-dot"/>状态与风险，始终可见</div></div><div className="ea-summary"><div><span>账户核心数据</span><strong>余额 / 净值 / 盈亏</strong><small>账户状态集中查看</small></div><div><span>全局风险状态</span><strong>额度 / 冷却 / 目标</strong><small>查看触发原因与处理范围</small></div></div><div className="ea-strategies">{["剥头皮管理","趋势管理"].map((name,i)=><div key={name}><div className="ea-card-head"><h4>{name}</h4><span>独立配置</span></div><dl><div><dt>持仓限制</dt><dd>按参数设置</dd></div><div><dt>管理方式</dt><dd>{i?"分阶段推进":"峰值回撤"}</dd></div><div><dt>风险状态</dt><dd>实时查看</dd></div></dl><div className="ea-demo-actions" aria-label="操作位置示意"><span>做空</span><span>做多</span><span>{i?"追踪管理":"转趋势"}</span></div><div className="ea-pending"><span>挂单价</span><div>价格输入区域</div></div></div>)}</div><div className="ea-bottom"><ShieldCheck size={14}/><span>执行依赖终端运行与交易条件</span><span className="mono">UI PREVIEW</span></div></div>}
const strategies=[{key:"scalp",name:"剥头皮管理",en:"SCALPING",title:"把短线交易的退出条件，提前定义好。",text:"独立设置手数、持仓上限、止损止盈；触发条件成立后，按峰值回撤规则管理退出。需要限制持仓时间时，可以启用超时退出。",items:["独立手数与持仓限制","峰值回撤管理","可选超时退出","策略统计与额度状态"],stages:["确认入场","建立保护","触发追踪","按条件退出"]},{key:"trend",name:"趋势管理",en:"TREND",title:"让一笔趋势持仓，有分阶段的管理方式。",text:"从初始保护开始，按配置逐步推进止损，在指定阶段减仓，并在后续条件满足时进入追踪。每个阶段都有预先定义的管理动作。",items:["独立手数与初始止损","多阶段止损推进","指定阶段减仓","后续追踪管理"],stages:["初始保护","止损推进","阶段减仓","追踪退出"]}];

export function EAPage(){return <Shell><section className="container product-hero"><div><Intro label="TradeEZ EA · MT5 交易管理工具" title={<>把交易管理，<br/>放在图表旁。</>}><p>将执行、持仓与风险管理集中在一张面板里。剥头皮与趋势两组模块，分别配置，各有节奏。</p><p>你负责交易判断，EA 按配置辅助后续管理。</p></Intro><div className="actions"><Action href="#management">查看管理功能</Action><Action href="/help/#getting-started" secondary>了解使用方式</Action></div></div><EAPreview/></section><div className="product-subnav"><div className="container"><span>TradeEZ EA</span><nav aria-label="EA 页面章节"><a href="#management">双策略管理</a><a href="#execution">下单辅助</a><a href="#risk">风险管理</a><a href="#sync">数据同步</a></nav></div></div>
<section id="management" className="section container"><SectionHead number="01 / POSITION MANAGEMENT" title={<>两种持仓节奏，<br/>各有自己的管理规则。</>} description="快节奏交易与趋势持仓，对止损推进、持仓时间和退出方式有不同要求。将设置分开，让管理逻辑更清楚。"/><Tabs defaultValue="scalp" className="strategy-tabs"><TabsList>{strategies.map(s=><TabsTrigger key={s.key} value={s.key}>{s.name}</TabsTrigger>)}</TabsList>{strategies.map(s=><TabsContent key={s.key} value={s.key}><div className="strategy-detail"><div><span className="chapter mono">{s.en}</span><h3>{s.title}</h3><p>{s.text}</p><div className="check-grid">{s.items.map(t=><span key={t}><Check size={15}/>{t}</span>)}</div></div><div className="stage-diagram"><span className="micro">{s.name} · 逻辑示意</span>{s.stages.map((t,i)=><div key={t}><span className="stage-number mono">0{i+1}</span><strong>{t}</strong><small>{i===0?"执行开始":i===3?"结束管理":"满足配置条件后"}</small></div>)}</div></div></TabsContent>)}</Tabs><p className="section-note">管理模块用于表达持仓处理方式，不等于自动识别行情或自主寻找入场信号。</p></section>
<section id="execution" className="tinted-section"><div className="section container split-section"><div><span className="chapter mono">02 / EXECUTION</span><h2>常用操作，<br/>在需要的位置。</h2><p className="section-lead">从市价操作到限价挂单，将方向、价格与策略归属放在相邻区域，便于执行前检查。</p><div className="operation-detail"><span className="micro">挂单操作区域 · 示意</span><div><span>挂单价</span><span className="price-field">待填写价格</span></div><div className="operation-labels"><span>限价空</span><span>限价多</span><span>现价偏移</span></div></div></div><Rows rows={[["下单与挂单辅助","通过策略卡片进行市价买卖，填写挂单价发起限价订单，或使用现价偏移快捷操作。交易仍受服务器规则及 EA 校验约束。"],["按范围处理持仓","按需要进行全部平仓、按策略平仓或盈利持仓处理。操作前核对当前品种、管理范围与策略归属。"],["满足条件后切换管理","符合转换条件的剥头皮持仓可以转入趋势管理；条件不满足时提示原因，让一次转换有明确依据。"]]}/></div></section>
<section id="risk" className="section container"><SectionHead number="03 / RISK CONTROL" title={<>把停止条件，<br/>和开仓条件一样认真地设置。</>} description="风险面板让额度、触发状态和冷却时间有一个固定的查看位置。先理解规则，再决定参数。"/><div className="risk-layout"><div className="risk-principle"><ShieldCheck size={32}/><h3>规则名称<br/><span>触发状态</span><br/>处理范围</h3><p>知道当前为什么限制，<br/>也知道限制作用在哪里。</p></div><div className="risk-grid">{[["分策略与全局限制","分别管理策略额度与全局净盈亏限制。触发后，相关 EA 开仓入口受到限制并显示原因。"],["连续亏损冷却","根据连续亏损条件进入冷却期，显示剩余时间，为下一次操作留下重新检查的间隔。"],["利润回撤保护","根据当日高水位和配置条件观察回落，不同条件对应禁开、相关平仓或锁定处理。"],["持仓数量与周目标","为策略设置持仓上限，查看周度目标进度与阶段提示，辅助安排交易节奏。"]].map(([title,text])=><div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></div><div className="boundary-note"><strong>理解管理边界</strong><p>EA 开仓限制不等于经纪商账户被全面锁定。当前品种的平仓处理不能视为覆盖全账户所有品种；滑点、网络与终端状态也会影响执行结果。</p></div></section>
<section id="sync" className="tinted-section"><div className="section container"><SectionHead number="04 / CONNECTED RECORDS" title={<>交易现场的记录，<br/>连接之后的复盘。</>} description="查看余额、净值、已实现与浮动盈亏，以及各策略持仓与日内表现。通过平仓明细和统计视图回顾当天交易。"/><div className="sync-flow"><div><Monitor/><strong>MT5 · TradeEZ EA</strong><p>成交记录<br/>账户与配置快照</p></div><div className="flow-connector"><span>需配置服务接入</span><ArrowRight/><small>按周期同步</small></div><div><BookOpen/><strong>TradeEZ 复盘平台</strong><p>交易归档与分类<br/>计划、分析与复盘</p><span className="status-tag">首版筹备中</span></div></div><p className="section-note">启用并完成接入后，按配置周期上报。同步时间与日志帮助核对记录；历史分析不替代实时持仓风险监控。</p></div></section><PageEnd title="执行之后，给交易一个清楚的解释。" description="了解配套平台如何连接交易事实、执行规则和下一步行动。" href="/platform/" label="预览复盘平台"/></Shell>}

const analysisRows=[["整体表现","当前筛选范围的盈亏、胜负分布与已实现回撤如何？","回到每一笔成交"],["交易模型","不同模型的样本与执行情况有什么差异？","核对模型分类"],["时间特征","交易时段与持仓时间，有哪些值得观察的特征？","查看同类样本"],["风险与 R","在有可靠初始风险的交易里，结果如何分布？","检查风险基准"],["错误与行为","哪些问题重复出现？哪些正向行为值得保留？","查看关联标签"],["规则执行","遵守、违规与证据不足的交易，分别是什么情况？","回看评价依据"]];
export function PlatformPage(){return <Shell><section className="container platform-hero"><Intro label="TradeEZ · 交易复盘平台" status="首版筹备中 · 功能设计预览" title={<>让交易历史，<br/>成为可以改进的经验。</>}><p>把真实成交、交易模型、执行规则、截图与每日计划组织在一起。解释一笔交易，也从多笔交易中看见自己。</p></Intro><div className="actions"><Action href="#features">查看首版功能</Action><Action href="#daily" secondary>查看每日流程</Action></div><div className="platform-preview-wrap"><ReviewPreview large/><aside><span className="chapter mono">BEYOND THE RESULT</span><h3>事实、判断、反思，<br/>各有自己的位置。</h3><p>原始成交保留事实。<br/>交易前记录留下判断。<br/>复盘解释实际执行。</p>{["保留完整交易过程","检查当时的规则版本","留下具体改进行动"].map((t,i)=><div className="preview-annotation" key={t}><span>0{i+1}</span><p>{t}</p></div>)}</aside></div></section><div className="product-subnav"><div className="container"><span>首版功能设计</span><nav aria-label="平台页面章节"><a href="#features">归档与标签</a><a href="#review">单笔复盘</a><a href="#rules">规则评价</a><a href="#analysis">整体分析</a><a href="#daily">每日习惯</a></nav></div></div>
<section id="features" className="section container"><SectionHead number="01 / YOUR TRADING LIBRARY" title={<>先保留事实，<br/>再建立自己的交易索引。</>} description="多个账号按同一套方式回顾。完整交易与原始成交互相关联，让结论始终能够回到具体记录。"/><div className="archive-grid"><div><h3>账号与成交，清楚归档。</h3><p>选择历史同步起点、管理接入密钥，查看同步日志与最新已同步交易的平仓时间。EA 参数以只读快照呈现，用于核对实际配置。</p><p>按账号、品种、方向、时间和编号查询；按列排序并查看价格、数量、费用与盈亏。对于有可靠关联的加仓、分批平仓，组织成完整交易供复盘。</p><div className="inline-note">关联依据不足的记录提示核对，不强行归并。</div></div><div className="tag-library"><div className="panel-caption"><strong>用自己的语言分类</strong><span>标签示例</span></div>{[["交易模型","趋势回踩","区间突破"],["执行行为","等待确认","提前入场"],["市场环境","震荡整理","趋势延续"],["交易情绪","平静","急于挽回"]].map(([name,...tags])=><div className="tag-row" key={name}><span>{name}</span><div>{tags.map((tag,i)=><span className={`tag-token ${i===0?"blue":""}`} key={tag}>{tag}</span>)}</div></div>)}<p>自定义名称、分组与说明；支持停用和合并，让标签随你的方法一起成长。</p></div></div></section>
<section id="review" className="tinted-section"><div className="section container"><SectionHead number="02 / TRADE REVIEW" title={<>回到入场当时，<br/>说明自己的判断。</>} description="简单交易可以简短复盘，典型交易再深入展开。记录值得保留的行为，也记录下一次需要改变的动作。"/><div className="review-phases">{[["BEFORE","交易前","为什么考虑这笔机会？","关联盘前场景、关注位置、触发条件与失效点。原先的记录保留时间，事后补写明确标注。"],["DURING","交易中","实际做了哪些决定？","结合成交时间线，补充加减仓、止损调整与退出理由。用截图保留当时看到的市场结构。"],["AFTER","交易后","下一次具体怎样做？","总结执行得好的地方，找出主要问题，并留下一个可执行的改进行动。"]].map(([en,title,q,text],i)=><div key={en}><span className="phase-num mono">0{i+1}<small>{en}</small></span><h3>{title}</h3><h4>{q}</h4><p>{text}</p></div>)}</div><p className="section-note">复盘支持草稿与修改记录。交易数据发生重要变化时，提示重新核对，并保留已有文字与依据。</p></div></section>
<section id="rules" className="section container split-section rules-section"><div><span className="chapter mono">03 / YOUR PLAYBOOK</span><h2>把自己的交易系统，<br/>写成可检查的规则。</h2><p className="section-lead">为模型定义适用环境、入场确认、风险要求和管理条件。结束后，按当时使用的版本逐项评价。</p><div className="rule-beliefs"><h3>结果与执行，分别呈现。</h3><p>盈利不自动代表遵守规则，亏损也不会自动降低执行评价。</p><h3>证据不足，明确留下空白。</h3><p>正式评分需要满足评价完整性要求。方法更新后，历史交易仍保留原来的规则版本。</p></div></div><div className="rules-demo"><div className="panel-caption"><strong>趋势回踩 · 规则检查</strong><span>设计示意</span></div><p className="micro">历史规则版本随交易保留</p>{[["触及计划内的关键区域","通过","pass"],["等待确认后再执行","未通过","fail"],["初始风险符合计划","无法判断","unknown"],["分批退出符合预设条件","不适用","na"]].map(([title,status,tone])=><div className="rule-demo-line" key={title}><span>{title}</span><span className={`rule-status ${tone}`}>{status}</span></div>)}<div className="evidence-note"><CircleDashed size={18}/><div><strong>评价尚未完整</strong><p>风险依据缺失，暂不生成正式执行分数。</p></div></div></div></section>
<section id="analysis" className="tinted-section"><div className="section container"><SectionHead number="04 / TRADING ANALYTICS" title={<>从一笔解释，<br/>走向一组可以核对的观察。</>} description="每个分组保留样本数量，并可回到相关交易。先确认统计范围，再看模型、时段、行为和执行的差异。"/><div className="analysis-table"><table><caption className="sr-only">首版整体交易分析方向</caption><thead><tr><th scope="col">分析方向</th><th scope="col">值得提出的问题</th><th scope="col">下一步核对</th></tr></thead><tbody>{analysisRows.map(([name,q,next])=><tr key={name}><th scope="row">{name}</th><td>{q}</td><td>{next}<ArrowUpRight size={14}/></td></tr>)}</tbody></table></div><div className="data-boundaries">{[["有依据，才计算。","缺少初始风险时不生成 R；缺少价格路径时，不计算最大有利或不利变动。"],["不同口径，清楚区分。","不同币种金额分别呈现。只有已实现数据时，明确称为已实现盈亏，不当作实时权益。"],["样本相关，不等于因果。","标签与结果之间的关系用于提出问题，不能凭少量样本证明策略有效。"]].map(([t,p])=><div key={t}><strong>{t}</strong><p>{p}</p></div>)}</div></div></section>
<section id="daily" className="section container"><SectionHead number="05 / A BETTER DAILY ROUTINE" title={<>今天的改进，<br/>从开盘前就开始。</>} description="盘前计划、盘中记录、盘后总结相互关联。把复盘结论转成下一次能做到的动作，逐步形成适合自己的节奏。"/><div className="daily-layout"><div className="daily-plan"><div className="panel-caption"><strong><CalendarDays size={17}/>今日交易计划</strong><span>设计预览</span></div><div className="plan-choice"><span>正常交易</span><span className="chosen">仅观察</span><span>计划休息</span></div>{[["市场与关注场景","等待价格回到关键区域，观察结构是否确认。"],["允许执行的条件","只有场景、确认与风险条件同时满足，才考虑入场。"],["今天的改进重点","在执行前完成检查，不把“接近条件”当成确认。"]].map(([t,p])=><div className="plan-entry" key={t}><span>{t}</span><p>{p}</p></div>)}<div className="plan-footer"><Check size={15}/>不交易，也可以完成有价值的一天。</div></div><Rows rows={[["盘前，明确执行与放弃条件","记录环境、关键位置、事件、允许模型与风险边界。确认后保留版本；盘中修订留下时间和原因，不改写此前交易的依据。"],["盘中，保留当时的想法","成交尚未同步时，先记录观察场景或交易意图。之后关联实际交易，区分原先的计划与事后补写的解释。"],["盘后，对照计划与实际","回顾已知交易、规则情况和待复盘事项。每日总结与单笔复盘分别跟进，未完成的复盘继续保留为待办。"],["下一次，落实一项具体行动","把“不要追单”变成“入场前完成确认清单”。持续跟踪行动，在周复盘中检查是否做到。"]]}/></div><div className="habit-line"><ListChecks/><div><h3>习惯以准备和复盘衡量。</h3><p>休息日不当作漏打卡，事后补录与按时完成分别统计，不通过增加交易次数评价纪律。</p></div></div></section><PageEnd title="先让日常流程，完整运行。" description="首版专注记录、规则、分析与每日复盘。AI、课程和回放属于后续方向。" href="/roadmap/" label="查看未来规划"/></Shell>}

const directions=[
["01","AI 复盘","让反馈回到证据。","将成交、规则检查、笔记和历史统计组织为复盘依据，探索单笔总结、重复问题归纳和同类比较。反馈应指向所依据的交易与规则，证据不足时明确说明。","关键盈亏与评分由确定的计算规则产生，AI 侧重解释与总结。","基于证据的反馈","交易记录|规则依据|问题归纳|行动建议"],
["02","课程与案例","从自己的问题，找到值得学习的内容。","围绕市场结构、价格行为、交易模型、风险管理和复盘方法组织知识，将概念、规则与案例关联。反复遇到的问题，可以继续进入相关课程和检查清单。","案例从人工整理与明确来源开始，公开使用用户交易需要另行授权与脱敏。","把学习连接到实践","问题标签|相关概念|正反案例|检查清单"],
["03","回放与练习","在历史场景中，练习识别与执行。","探索历史行情回放、手动回测与场景练习。在逐步展开的价格中记录判断，再查看后续结果，用同一套模型与规则检查执行。","需要可靠行情数据及相应使用条件支持，尚不属于首版。","让判断留下过程","历史场景|逐步观察|记录决策|回顾结果"],
["04","个性化学习","从重复问题中，安排下一项练习。","结合确认后的错误、规则执行与练习记录，探索更有针对性的学习路径。比较相似模型、方向和环境下的交易，让改进问题更加具体。","相似不意味着结果可复制；比较需要保留样本量、条件与差异。","循序验证自己的方法","重复问题|选择练习|执行记录|再次验证"]];
export function RoadmapPage(){return <Shell><section className="container editorial-hero"><Intro label="THE ROAD AHEAD · 产品演进" status="规划方向 · 不代表已上线能力" title={<>从记录与复盘，<br/>走向学习、练习和验证。</>}><p>交易记录会不断积累。下一步，是让复盘中的问题连接到相关知识、相似案例和练习，再回到实际执行中观察变化。</p></Intro></section><section className="container roadmap-overview"><div className="roadmap-current"><span className="chapter mono">NOW / 首版筹备</span><h2>先把事实记录完整，<br/>把自己的方法说明白。</h2><p>账号与成交归档、分组标签、单笔复盘、规则评价、整体分析，以及从盘前到盘后的每日流程。</p><Link className="text-link" href="/platform/">了解首版完整范围<ArrowUpRight size={16}/></Link></div><div className="roadmap-direction">{[["记录与复盘","首版筹备"],["学习与练习","后续方向"],["研究与验证","长期探索"]].map(([t,s],i)=><div key={t}><span className="mono">0{i+1}</span><strong>{t}</strong><small>{s}</small></div>)}</div></section><section className="section container roadmap-list"><SectionHead number="NEXT / LEARN FROM YOUR RECORDS" title="让发现的问题，有继续前进的方向。"/>{directions.map(([num,type,title,text,note,diagramTitle,flow])=><article className="roadmap-item" key={num}><div className="roadmap-marker"><span className="mono">{num}</span><span>{type}</span></div><div><span className="status-tag">后续规划</span><h3>{title}</h3><p>{text}</p><p className="roadmap-footnote">{note}</p></div><div className="concept-diagram"><span className="micro">{diagramTitle}</span>{flow.split("|").map((step,i)=><div key={step}><span className="concept-dot"/>{step}{i<3&&<span className="concept-line"/>}</div>)}</div></article>)}</section><section className="tinted-section"><div className="section container split-section"><div><span className="chapter mono">LATER / RESEARCH</span><h2>补充更完整的上下文，<br/>再检验自己的方法。</h2><span className="status-tag intro-status">长期探索</span></div><div className="long-term"><h3>市场背景与进阶研究</h3><p>探索经济事件、黄金相关市场背景，以及在数据条件允许时提供订单流、成交量分布等研究资料。</p><p>更长期的方向包括策略条件表达、自动回测，以及模型和错误的辅助识别。这些能力需要独立的数据、验证与产品设计。</p><div className="inline-note">功能范围、顺序与开放安排将根据验证和反馈调整，当前不作具体上线日期承诺。</div></div></div></section><PageEnd title="现在，从建立自己的交易记录开始。" description="未来功能会继续演进，结构化复盘不需要等待 AI 才能开始。" href="/platform/" label="了解首版设计"/></Shell>}

export function HelpPage(){return <Shell><section className="container editorial-hero help-hero"><Intro label="GETTING STARTED · 使用指南" title={<>先理解工具，<br/>再建立自己的使用节奏。</>}><p>从运行环境、管理参数到复盘流程，了解 TradeEZ 如何配合你的交易方式。</p></Intro><div className="actions"><Action href="#getting-started">EA 使用准备</Action><Action href="#faq" secondary>查看常见问题</Action></div></section><section id="getting-started" className="section container guide-section"><div className="guide-heading"><span className="chapter mono">01 / EA SETUP</span><h2>从确认参数开始。</h2><p>当前重点面向 MT5 黄金日内交易场景。安装与运行前，先在自己的环境中核对功能及管理范围。</p></div><Rows rows={[["准备运行环境","确认使用 MetaTrader 5，检查账户类型、交易品种、交易权限及 EA 的适配条件。自动管理需要终端持续运行，并保持必要的网络连接。"],["加载 EA，核对管理参数","按发布版本的安装说明加载 EA。确认策略识别、下单手数、持仓上限、止损管理及风险限制，不直接将示例参数当作自己的交易方案。"],["检查面板，再进行操作","确认交易时段、策略状态、持仓归属及风险提示。理解按钮的处理范围，在实际使用环境中验证管理动作是否符合预期。"],["按需配置平台接入","平台开放后，创建同步账号、选择历史起点，填写密钥和连接设置。检查同步日志、最新已同步平仓时间，并核对 EA 配置快照。"],["持续核对并保留记录","留意退出、减仓与风险触发后的实际结果。出现异常时，结合终端日志、同步状态及服务器返回信息定位问题。"]]}/></section><section className="tinted-section"><div className="section container"><SectionHead number="02 / FIRST REVIEW" title="第一次复盘，从四个问题开始。" description="不必一开始就写很长。先说清一笔交易，再逐步建立自己的标签、模型与规则。以下为平台首版设计流程。"/><div className="question-grid">{[["为什么做？","记录场景、触发与失效条件，关联盘前计划。"],["实际做了什么？","对照成交与截图，说明入场、管理及退出。"],["规则做到了吗？","按当时规则逐项检查，证据不足时保留未知。"],["下一次改变什么？","选择一项具体行动，带入下一次交易准备。"]].map(([title,text],i)=><div key={title}><span className="chapter mono">0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section><section id="faq" className="section container help-faq"><div><span className="chapter mono">03 / QUESTIONS & ANSWERS</span><h2>常见问题</h2><p>关于产品分工、使用边界、数据与首版范围。</p></div><FAQList/></section><PageEnd title="找到适合你的下一步。" description="先了解执行工具，再看看交易记录如何进入持续复盘。" href="/ea/" label="了解 TradeEZ EA"/></Shell>}
